package com.nexovian.mazemuncher;

import android.app.*;import android.os.*;import android.graphics.*;import android.view.*;import android.content.*;import java.util.*;
public class MainActivity extends Activity{@Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setFlags(1024,1024);setContentView(new GameView(this));}}
class GameView extends View{
 static final int C=19,R=23; Paint p=new Paint(3); Random rnd=new Random(); int[][] m=new int[R][C];
 float px,py; int dir=1,want=1,score=0,lives=3,level=1,pellets; boolean over=false; float sx,sy; long last; ArrayList<Enemy> es=new ArrayList<>();
 final String[] maze={"###################","#........#........#","#.###.##.#.##.###.#","#o###.##.#.##.###o#","#.................#","#.###.#.#####.#.###","#.....#...#...#...#","#####.### # ###.###","    #.#       #.#  ","#####.# ## ## #.###","     .  #   #  .   ","#####.# ##### #.###","    #.#       #.#  ","#####.# ##### #.###","#........#........#","#.###.##.#.##.###.#","#o..#.... ....#..o#","###.#.#.#####.#.###","#.....#...#...#...#","#.#######.#.#######","#.................#","#.................#","###################"};
 GameView(Context c){super(c);p.setTypeface(Typeface.DEFAULT_BOLD);setBackgroundColor(Color.rgb(7,10,24));reset();last=System.nanoTime();}
 void reset(){pellets=0;for(int r=0;r<R;r++)for(int c=0;c<C;c++){char q=maze[r].charAt(c);m[r][c]=q=='#'?1:q=='.'?2:q=='o'?3:0;if(m[r][c]>1)pellets++;}px=9;py=16;dir=1;want=1;es.clear();es.add(new Enemy(9,10,0xffff465f));es.add(new Enemy(8,10,0xff00dcff));es.add(new Enemy(10,10,0xffff82dc));es.add(new Enemy(9,12,0xffffa53c));}
 boolean open(int x,int y){return y>=0&&y<R&&x>=0&&x<C&&m[y][x]!=1;}
 void player(float dt){int[] dx={0,1,0,-1},dy={-1,0,1,0};float speed=4.2f+level*.08f,remain=speed*dt;while(remain>0){int cx=Math.round(px),cy=Math.round(py);float dc=Math.abs(px-cx)+Math.abs(py-cy);if(dc<.06f){px=cx;py=cy;if(open(cx+dx[want],cy+dy[want]))dir=want;if(!open(cx+dx[dir],cy+dy[dir]))break;}float step=Math.min(remain,.045f);px+=dx[dir]*step;py+=dy[dir]*step;remain-=step;if(px<-.5f)px=C-.5f;if(px>C-.5f)px=-.5f;}int x=Math.round(px),y=Math.round(py);if(y>=0&&y<R&&x>=0&&x<C&&m[y][x]>1){score+=m[y][x]==3?50:10;m[y][x]=0;if(--pellets<=0){level++;reset();}}}
 void tick(float dt){if(over)return;player(dt);for(Enemy e:es){e.move(dt,m,rnd);float x=e.x-px,y=e.y-py;if(x*x+y*y<.35f){if(--lives<=0)over=true;else{px=9;py=16;dir=want=1;}break;}}}
 @Override protected void onDraw(Canvas c){super.onDraw(c);long n=System.nanoTime();float dt=Math.min(.025f,(n-last)/1e9f);last=n;tick(dt);float w=getWidth(),h=getHeight(),top=90,cell=Math.min(w/C,(h-top-120)/R),ox=(w-cell*C)/2;
 p.setTextAlign(Paint.Align.LEFT);p.setTextSize(32);p.setColor(Color.WHITE);c.drawText("MAZE MUNCHER",20,40,p);p.setTextSize(20);p.setColor(0xff82f5ff);c.drawText("SCORE "+score,20,70,p);p.setColor(0xffffd241);c.drawText("LIVES "+lives,w*.43f,70,p);p.setColor(0xffbe8cff);c.drawText("LV "+level,w*.78f,70,p);
 for(int r=0;r<R;r++)for(int q=0;q<C;q++){float x=ox+q*cell,y=top+r*cell;if(m[r][q]==1){p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(Math.max(2,cell*.1f));p.setColor(0xff5046ff);c.drawRoundRect(x+2,y+2,x+cell-2,y+cell-2,cell*.2f,cell*.2f,p);p.setStyle(Paint.Style.FILL);}else if(m[r][q]>1){p.setColor(m[r][q]==3?0xffff78d2:0xfff5e6b4);c.drawCircle(x+cell/2,y+cell/2,m[r][q]==3?cell*.16f:cell*.07f,p);}}
 float x=ox+(px+.5f)*cell,y=top+(py+.5f)*cell;p.setColor(0xff50ff91);c.drawCircle(x,y,cell*.38f,p);for(Enemy e:es)e.draw(c,p,ox,top,cell);
 float by=h-58;p.setTextAlign(Paint.Align.CENTER);p.setTextSize(26);p.setColor(0xff82f5ff);c.drawText("◀     ▲     ▼     ▶",w/2,by,p);p.setTextSize(15);p.setColor(Color.LTGRAY);c.drawText("DESLIZE OU TOQUE NOS CONTROLES",w/2,h-20,p);
 if(over){p.setColor(0xdd070a18);c.drawRect(0,h*.35f,w,h*.65f,p);p.setTextSize(44);p.setColor(Color.WHITE);c.drawText("GAME OVER",w/2,h*.47f,p);p.setTextSize(21);c.drawText("TOQUE PARA RECOMEÇAR",w/2,h*.55f,p);}p.setTextAlign(Paint.Align.LEFT);postInvalidateOnAnimation();}
 @Override public boolean onTouchEvent(MotionEvent e){if(e.getAction()==MotionEvent.ACTION_DOWN){sx=e.getX();sy=e.getY();if(over){score=0;lives=3;level=1;over=false;reset();invalidate();return true;}if(sy>getHeight()-105){float q=getWidth()/4f;want=sx<q?3:sx<2*q?0:sx<3*q?2:1;invalidate();return true;}return true;}if(e.getAction()==MotionEvent.ACTION_UP){float dx=e.getX()-sx,dy=e.getY()-sy;if(Math.max(Math.abs(dx),Math.abs(dy))>18)want=Math.abs(dx)>Math.abs(dy)?(dx>0?1:3):(dy>0?2:0);invalidate();return true;}return true;}
}
class Enemy{float x,y;int d,color;Enemy(float x,float y,int c){this.x=x;this.y=y;color=c;}void move(float dt,int[][]m,Random r){int[]dx={0,1,0,-1},dy={-1,0,1,0};int cx=Math.round(x),cy=Math.round(y);if(Math.abs(x-cx)+Math.abs(y-cy)<.05){x=cx;y=cy;ArrayList<Integer>o=new ArrayList<>();for(int k=0;k<4;k++){int nx=cx+dx[k],ny=cy+dy[k];if(ny>=0&&ny<m.length&&nx>=0&&nx<m[0].length&&m[ny][nx]!=1&&k!=(d+2)%4)o.add(k);}if(!o.isEmpty())d=o.get(r.nextInt(o.size()));}float s=2.7f*dt;x+=dx[d]*s;y+=dy[d]*s;}void draw(Canvas c,Paint p,float ox,float top,float cell){float a=ox+(x+.5f)*cell,b=top+(y+.5f)*cell;p.setColor(color);c.drawRoundRect(a-cell*.34f,b-cell*.34f,a+cell*.34f,b+cell*.34f,cell*.25f,cell*.25f,p);p.setColor(Color.WHITE);c.drawCircle(a-cell*.13f,b-cell*.08f,cell*.09f,p);c.drawCircle(a+cell*.13f,b-cell*.08f,cell*.09f,p);}}
