//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class Controle
    {
        public int Id { get; set; }
        public int Pedido { get; set; }
        public string Cripto { get; set; }
        public string Operacao { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public Nullable<decimal> Valor_RS { get; set; }
        public Nullable<int> Qtde_Cripto { get; set; }
        public Nullable<decimal> Taxa_RS { get; set; }
        public Nullable<decimal> Taxa_Cripto { get; set; }
        public string Hash { get; set; }
        public string Banco { get; set; }
        public int Id_Cliente { get; set; }
        public string Cliente { get; set; }
        public string Ref { get; set; }
        public Nullable<bool> Statu_Operacao { get; set; }
    }
}
